Change to more tick efficient solution
LlemonDuck/tombs-of-amascut pull request #46
Opened 2023-01-10 01:15 UTC by PowContent

The provided solution is optimised for tick efficiency given a start tile by the tablet and a end tile at the door. Sanity checked, values add up when tested against a lookup array:
```[9, 3, 7, 2, 9, 7, 6, 4, 1, 1, 8, 6, 3, 8, 5, 6, 2, 7, 2, 4, 1, 9, 5, 4, 3]```

2023-01-10 01:17 UTC, PowContent commented
[kephri solutions.zip](https://github.com/LlemonDuck/tombs-of-amascut/files/10378121/kephri.solutions.zip)
All Optimal Solutions by number

2023-01-17 05:06 UTC, LlemonDuck requested changes
Just the one solution needs a second look.

Since (I expect) you're making a change for that, can you also make sure the sets use increasing order for their values?

2023-01-17 05:06 UTC, LlemonDuck commented on src/main/java/com/duckblade/osrs/toa/features/scabaras/overlay/AdditionPuzzleSolver.java
> +		.put(38, ImmutableSet.of(0, 5, 6, 12, 18, 24))
I believe this one is missing 10. Can you confirm?

![image](https://user-images.githubusercontent.com/1868974/212814030-25ed67f4-cea3-41b8-9e11-6429105ebdb3.png)

2023-01-26 07:47 UTC, LlemonDuck commented
added in daadc1d1b1c2d7f7a0ac932c89e183b4af2ef681

2023-01-26 07:47 UTC, closed without merging